spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  application:
    name: turbine
turbine:
  aggregator:
    cluster-config:
      - zk-client-hystrix
  app-config: zk-client-hystrix
server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always

