spring:
  application:
    name: tcoding-client
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:

#        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
server:
  port: 9002

